<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
switch ($screen) {
    case 'settings':
        echo '<div class="row" id="cms-settings">';
            echo '<div class="small-12 columns">';
                echo '<div class="row">';
                    echo '<div class="small-12 columns">';
                        echo '<h3 class="left">'.lang('cms_settings').'</h3>';
                    echo '</div>';
                echo '</div>';
                echo form_open_multipart(current_url(), 'id="cms-settings-form-settings"');
                    echo '<div class="row">';
                        echo '<div class="small-2 columns">';
                            echo form_label(lang('cms_settings_title'));
                        echo '</div>';
                        echo '<div class="small-10 columns left">';
                            echo form_input(array('name'=>'layout_site_title'), set_value('layout_site_title', get_setting('layout_site_title')));
                        echo '</div>';
                    echo '</div>';
                    echo '<div class="row">';
                        echo '<div class="small-2 columns">';
                            echo form_label(lang('cms_settings_description'));
                        echo '</div>';
                        echo '<div class="small-10 columns left">';
                            echo form_textarea(array('name'=>'layout_site_description', 'rows'=>'3'), set_value('layout_site_description', get_setting('layout_site_description')));
                        echo '</div>';
                    echo '</div>';
                    echo '<div class="row">';
                        echo '<div class="small-2 columns">';
                            echo form_label(lang('cms_settings_content_homepage'));
                        echo '</div>';
                        echo '<div class="small-10 columns left">';
                            echo form_textarea(array('name'=>'layout_site_home_content', 'rows'=>'6'), set_value('layout_site_home_content', get_setting('layout_site_home_content')));
                        echo '</div>';
                    echo '</div>';
                    echo '<div class="row">';
                        echo '<div class="small-2 columns">';
                            echo form_label(lang('cms_settings_footer_text'));
                        echo '</div>';
                        echo '<div class="small-10 columns left">';
                            echo form_textarea(array('name'=>'layout_site_footer', 'rows'=>'3'), set_value('layout_site_footer', get_setting('layout_site_footer')));
                        echo '</div>';
                    echo '</div>';
                    echo '<div class="row">'; 
                        echo '<div class="small-2 columns">';
                            echo form_label(lang('cms_settings_logo'));
                        echo '</div>';
                        if (get_setting('layout_logo') == NULL):
                            echo '<div class="small-5 columns">';
                                echo form_upload(array('name'=>'layout_logo'), set_value('layout_logo'));
                            echo '</div>';
                            echo '<div class="small-2 columns left">';
                                echo form_submit(array('name'=>'upload_logo', 'class'=>'button success tiny'), lang('cms_settings_send_image'));
                            echo '</div>';
                        else:
                            echo '<div class="small-1 columns">';
                                echo thumb(get_setting('layout_logo'));
                            echo '</div>';
                            echo '<div class="small-2 columns left">';
                                echo form_submit(array('name'=>'delete_logo', 'class'=>'button alert tiny'), lang('cms_settings_remove_image'));
                            echo '</div>';
                        endif;
                    echo '</div>';
                    echo '<div class="row">'; 
                        echo '<div class="small-2 columns">';
                            echo form_label(lang('cms_settings_homepage_capa'));
                        echo '</div>';
                        if (get_setting('layout_capa') == NULL):
                            echo '<div class="small-5 columns">';
                                echo form_upload(array('name'=>'layout_capa'), set_value('layout_capa'));
                            echo '</div>';
                            echo '<div class="small-2 columns left">';
                                echo form_submit(array('name'=>'upload_capa', 'class'=>'button success tiny'), lang('cms_settings_send_image'));
                            echo '</div>';
                        else:
                            echo '<div class="small-1 columns">';
                                echo thumb(get_setting('layout_capa'));
                            echo '</div>';
                            echo '<div class="small-2 columns left">';
                                echo form_submit(array('name'=>'delete_capa', 'class'=>'button alert tiny'), lang('cms_settings_remove_image'));
                            echo '</div>';
                        endif;
                    echo '</div>';
                    echo '<div class="row">';
                        echo '<div class="small-2 columns">';
                            echo form_label(lang('cms_settings_homepage'));
                        echo '</div>';
                        echo '<div class="small-10 columns left">';
                            $options = array();
                            $options['home'] = '--> '.lang('cms_settings_homepage_site');
                            $options['blog'] = '--> '.lang('cms_settings_homepage_blog');
                            $this->db->where('post_status', 'publish');
                            $query_pages = $this->posts->get_by_type('page')->result();
                            foreach ($query_pages as $line):
                                $options[$line->post_slug] = $line->post_title;
                            endforeach;
                            echo form_dropdown('site_page_home', $options, get_setting('site_page_home'));
                        echo '</div>';
                    echo '</div>';
                    echo '<div class="row">';
                        echo '<div class="small-2 columns">';
                            echo form_label(lang('cms_settings_num_posts_blog'));
                        echo '</div>';
                        echo '<div class="small-10 columns left">';
                            echo form_input(array('name'=>'site_blog_num_posts'), set_value('site_blog_num_posts', get_setting('site_blog_num_posts')));
                        echo '</div>';
                    echo '</div>';
                    echo '<div class="row">';
                        echo '<div class="small-2 columns">';
                            echo form_label(lang('cms_settings_moderation_required'));
                        echo '</div>';
                        echo '<div class="small-10 columns left">';
                            $options = array();
                            $options['0'] = 'Não';
                            $options['1'] = 'Sim';
                            echo form_dropdown('site_comments_moderation', $options, get_setting('site_comments_moderation'));
                        echo '</div>';
                    echo '</div>';
                    echo '<div class="row">';
                        echo '<div class="small-12 columns">';
                            echo form_checkbox(array('name'=>'site_menu_tools', 'id'=>'site_menu_tools'), '1', (get_setting('site_menu_tools')==1) ? TRUE : FALSE).form_label(' '.lang('cms_settings_menu_site'), 'site_menu_tools');
                        echo '</div>';
                    echo '</div>';
                    echo '<div class="row">';
                        echo '<div class="small-12 columns">';
                            echo form_checkbox(array('name'=>'layout_model', 'id'=>'layout_model'), '1', (get_setting('layout_model')==1) ? TRUE : FALSE).form_label(' '.lang('cms_settings_active_model'), 'layout_model');
                        echo '</div>';
                    echo '</div>';
                    echo '<div class="small-12">';
                        echo form_submit(array('name'=>'save', 'class'=>'button radius small tiny right'), lang('cms_settings_save'));
                    echo '</div>';
                    if (get_setting('layout_model') == 1):
                        echo '<div class="row">';
                            echo '<div class="small-12 columns">';
                                echo '<h5 class="left">'.lang('cms_settings_layout').'</h5>';
                            echo '</div>';
                        echo '</div>';
                        echo '<div class="row">';
                            echo '<div class="small-12 columns">';
                                echo '<dl class="tabs vertical" data-tab>';
                                    echo '<dd class="active"><a href="#tab-1">'.lang('cms_settings_structure').'</a></dd>';
                                    echo '<dd><a href="#tab-2">'.lang('cms_settings_texts').'</a></dd>';
                                    echo '<dd><a href="#tab-3">'.lang('cms_settings_header').'</a></dd>';
                                    echo '<dd><a href="#tab-4">'.lang('cms_settings_sidebar').'</a></dd>';
                                    echo '<dd><a href="#tab-5">'.lang('cms_settings_pages').'</a></dd>';
                                    echo '<dd><a href="#tab-6">'.lang('cms_settings_images').'</a></dd>';
                                    echo '<dd><a href="#tab-7">'.lang('cms_settings_footer').'</a></dd>';
                                    echo '<dd><a href="#tab-8">'.lang('cms_settings_social').'</a></dd>';
                                    echo '<dd><a href="#tab-9">'.lang('cms_settings_css').'</a></dd>';
                                echo '</dl>';
                                echo '<div class="tabs-content vertical">';
                                    echo '<div class="content active" id="tab-1">';
                                        echo '<div class="row">';
                                            echo '<h5>'.lang('cms_settings_structure_background').'</h5>';
                                            echo '<div class="row">';
                                                echo '<div class="small-6 columns">';
                                                    echo form_label(lang('cms_settings_structure_backcolor'));
                                                    echo form_input(array('name'=>'layout_background', 'id'=>'layout_background'), set_value('layout_background', get_setting('layout_background')));
                                                echo '</div>';
                                            echo '</div>';
                                            echo '<div class="row">'; 
                                                echo '<div class="small-12 columns">';
                                                    echo form_label(lang('cms_settings_structure_backimage'));
                                                echo '</div>';
                                                if (get_setting('layout_background_image') == NULL):
                                                    echo '<div class="small-6 columns">';
                                                        echo form_upload(array('name'=>'layout_background_image'), set_value('layout_background_image'));
                                                    echo '</div>';
                                                    echo '<div class="small-2 columns left">';
                                                        echo form_submit(array('name'=>'upload_background', 'class'=>'button success tiny'), lang('cms_settings_send_image'));
                                                    echo '</div>';
                                                else:
                                                    echo '<div class="small-1 columns">';
                                                        echo thumb(get_setting('layout_background_image'));
                                                    echo '</div>';
                                                    echo '<div class="small-2 columns left">';
                                                        echo form_submit(array('name'=>'delete_background', 'class'=>'button alert tiny'), lang('cms_settings_remove_image'));
                                                    echo '</div>';
                                                endif;
                                            echo '</div>';
                                        echo '</div>';
                                        echo '{modal}';
                                        echo '<div class="row">';
                                            echo '<h5>'.lang('cms_settings_structure_widths').'</h5>';
                                            echo '<div class="row">';
                                                echo '<div class="small-12 columns">';
                                                    echo form_label(lang('cms_settings_structure_width_ent'));
                                                    echo form_input(array('name'=>'layout_width_site'), set_value('layout_width_site', get_setting('layout_width_site')));
                                                echo '</div>';
                                                echo '<div class="small-8 columns">';
                                                    echo form_label(lang('cms_settings_structure_width_page'));
                                                    echo form_input(array('name'=>'layout_width_content'), set_value('layout_width_content', get_setting('layout_width_content')));
                                                echo '</div>';
                                                echo '<div class="small-4 columns">';
                                                    echo form_label(lang('cms_settings_structure_width_side'));
                                                    echo form_input(array('name'=>'layout_width_sidebar'), set_value('layout_width_sidebar', get_setting('layout_width_sidebar')));
                                                echo '</div>';
                                            echo '</div>';
                                        echo '</div>';
                                        echo '<div class="row">';
                                            echo '<h5>'.lang('cms_settings_structure_sidebar').'</h5>';
                                            echo '<div class="row">';
                                                echo '<div class="small-3 columns">';
                                                    echo form_label(lang('cms_settings_structure_sidbar_pos'));
                                                    $options = array(''=>'', 'right'=>lang('cms_settings_structure_right'),'left'=>lang('cms_settings_structure_left'));
                                                    echo form_dropdown('layout_sidebar_position', $options, get_setting('layout_sidebar_position'));
                                                echo '</div>';
                                            echo '</div>';
                                        echo '</div>';
                                    echo '</div>';
                                    echo '<div class="content" id="tab-2">';
                                        echo '<div class="row">';
                                            echo '<h5>'.lang('cms_settings_texts').'</h5>';
                                            echo '<div class="small-6 columns">';
                                                echo form_label(lang('cms_settings_texts_font'));
                                                $options = array(''=>'','helvetica'=>'"Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif', 'verdana'=>'Verdana, Geneva, sans-serif','georgia'=>'Georgia, "Times New Roman", Times, serif','courier'=>'"Courier New", Courier, monospace','arial'=>'Arial, Helvetica, sans-serif','tahoma'=>'Tahoma, Geneva, sans-serif','trebuchet'=>'"Trebuchet MS", Arial, Helvetica, sans-serif','arialblack'=>'"Arial Black", Gadget, sans-serif','times'=>'"Times New Roman", Times, serif','palatino'=>'"Palatino Linotype", "Book Antiqua", Palatino, serif','lucida'=>'"Lucida Sans Unicode", "Lucida Grande", sans-serif','serif'=>'"MS Serif", "New York", serif','monaco'=>'"Lucida Console", Monaco, monospace','comic'=>'"Comic Sans MS", cursive',);
                                                echo form_dropdown('layout_text_font', $options, set_value('"Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif', get_setting('layout_text_font')));
                                            echo '</div>';
                                            echo '<div class="small-3 columns">';
                                                echo form_label(lang('cms_settings_texts_font_size'));
                                                $options = array(''=>'','8px'=>'8px','9px'=>'9px','10px'=>'10px','11px'=>'11px','12px'=>'12px','14px'=>'14px','16px'=>'16px','20px'=>'20px','24px'=>'24px','28px'=>'28px','36px'=>'36px','48px'=>'48px',);
                                                echo form_dropdown('layout_text_size', $options, set_value('12px', get_setting('layout_text_size')));
                                            echo '</div>';
                                            echo '<div class="small-3 columns">';
                                                echo form_label(lang('cms_settings_texts_color'));
                                                echo form_input(array('name'=>'layout_text_color', 'id'=>'layout_text_color'), set_value('layout_text_color', get_setting('layout_text_color')));
                                            echo '</div>';
                                        echo '</div>';
                                        echo '<div class="row">';
                                            echo '<h5>'.lang('cms_settings_texts_links').'</h5>';
                                            echo '<div class="small-3 columns">';
                                                echo form_label(lang('cms_settings_texts_links_color'));
                                                echo form_input(array('name'=>'layout_link_color', 'id'=>'layout_link_color'), set_value('layout_link_color', get_setting('layout_link_color')));
                                            echo '</div>';
                                            echo '<div class="small-3 columns">';
                                                echo form_label(lang('cms_settings_texts_links_visited'));
                                                echo form_input(array('name'=>'layout_link_visited', 'id'=>'layout_link_visited'), set_value('layout_link_visited', get_setting('layout_link_visited')));
                                            echo '</div>';
                                            echo '<div class="small-3 left columns">';
                                                echo form_label(lang('cms_settings_texts_links_hight'));
                                                echo form_input(array('name'=>'layout_link_hover', 'id'=>'layout_link_hover'), set_value('layout_link_hover', get_setting('layout_link_hover')));
                                            echo '</div>';
                                        echo '</div>';
                                    echo '</div>';
                                    echo '<div class="content" id="tab-3">';
                                        echo '<div class="row">';
                                            echo '<h5>'.lang('cms_settings_header_background').'</h5>';
                                            echo '<div class="small-3 columns">';
                                                echo form_label(lang('cms_settings_header_backcolor'));
                                                echo form_input(array('name'=>'layout_header_background', 'id'=>'layout_header_background'), set_value('layout_header_background', get_setting('layout_header_background')));
                                            echo '</div>';
                                        echo '</div>';
                                        echo '<div class="row">';
                                            echo '<h5>'.lang('cms_settings_header_title').'</h5>';
                                            echo '<div class="small-6 columns">';
                                                echo form_label(lang('cms_settings_header_title_font'));
                                                $options = array(''=>'','helvetica'=>'"Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif', 'verdana'=>'Verdana, Geneva, sans-serif','georgia'=>'Georgia, "Times New Roman", Times, serif','courier'=>'"Courier New", Courier, monospace','arial'=>'Arial, Helvetica, sans-serif','tahoma'=>'Tahoma, Geneva, sans-serif','trebuchet'=>'"Trebuchet MS", Arial, Helvetica, sans-serif','arialblack'=>'"Arial Black", Gadget, sans-serif','times'=>'"Times New Roman", Times, serif','palatino'=>'"Palatino Linotype", "Book Antiqua", Palatino, serif','lucida'=>'"Lucida Sans Unicode", "Lucida Grande", sans-serif','serif'=>'"MS Serif", "New York", serif','monaco'=>'"Lucida Console", Monaco, monospace','comic'=>'"Comic Sans MS", cursive',);
                                                echo form_dropdown('layout_title_font', $options, set_value('"Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif', get_setting('layout_title_font')));
                                            echo '</div>';
                                            echo '<div class="small-3 columns">';
                                                echo form_label(lang('cms_settings_header_title_size'));
                                                $options = array(''=>'','8px'=>'8px','9px'=>'9px','10px'=>'10px','11px'=>'11px','12px'=>'12px','14px'=>'14px','16px'=>'16px','20px'=>'20px','24px'=>'24px','28px'=>'28px','36px'=>'36px','48px'=>'48px',);
                                                echo form_dropdown('layout_title_size', $options, set_value('28px', get_setting('layout_title_size')));
                                            echo '</div>';
                                            echo '<div class="small-3 columns">';
                                                echo form_label(lang('cms_settings_header_title_color'));
                                                echo form_input(array('name'=>'layout_title_color', 'id'=>'layout_title_color'), set_value('layout_title_color', get_setting('layout_title_color')));
                                            echo '</div>';
                                        echo '</div>';
                                        echo '<div class="row">';
                                            echo '<h5>'.lang('cms_settings_header_description').'</h5>';
                                            echo '<div class="small-6 columns">';
                                                echo form_label(lang('cms_settings_header_descrip_font'));
                                                $options = array(''=>'','helvetica'=>'"Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif', 'verdana'=>'Verdana, Geneva, sans-serif','georgia'=>'Georgia, "Times New Roman", Times, serif','courier'=>'"Courier New", Courier, monospace','arial'=>'Arial, Helvetica, sans-serif','tahoma'=>'Tahoma, Geneva, sans-serif','trebuchet'=>'"Trebuchet MS", Arial, Helvetica, sans-serif','arialblack'=>'"Arial Black", Gadget, sans-serif','times'=>'"Times New Roman", Times, serif','palatino'=>'"Palatino Linotype", "Book Antiqua", Palatino, serif','lucida'=>'"Lucida Sans Unicode", "Lucida Grande", sans-serif','serif'=>'"MS Serif", "New York", serif','monaco'=>'"Lucida Console", Monaco, monospace','comic'=>'"Comic Sans MS", cursive',);
                                                echo form_dropdown('layout_description_font', $options, set_value('"Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif', get_setting('layout_description_font')));
                                            echo '</div>';
                                            echo '<div class="small-3 columns">';
                                                echo form_label(lang('cms_settings_header_descrip_size'));
                                                $options = array(''=>'','8px'=>'8px','9px'=>'9px','10px'=>'10px','11px'=>'11px','12px'=>'12px','14px'=>'14px','16px'=>'16px','20px'=>'20px','24px'=>'24px','28px'=>'28px','36px'=>'36px','48px'=>'48px',);
                                                echo form_dropdown('layout_description_size', $options, set_value('14px', get_setting('layout_description_size')));
                                            echo '</div>';
                                            echo '<div class="small-3 columns">';
                                                echo form_label(lang('cms_settings_header_descrip_color'));
                                                echo form_input(array('name'=>'layout_description_color', 'id'=>'layout_description_color'), set_value('layout_description_color', get_setting('layout_description_color')));
                                            echo '</div>';
                                        echo '</div>';
                                    echo '</div>';
                                    echo '<div class="content" id="tab-4">';
                                        echo '<div class="row">';
                                            echo '<h5>'.lang('cms_settings_sidebar_background').'</h5>';
                                            echo '<div class="small-3 columns">';
                                                echo form_label(lang('cms_settings_sidebar_back_tabs'));
                                                echo form_input(array('name'=>'layout_sidebar_tabs_background', 'id'=>'layout_sidebar_tabs_background'), set_value('layout_sidebar_tabs_background', get_setting('layout_sidebar_tabs_background')));
                                            echo '</div>';
                                            echo '<div class="small-3 columns left">';
                                                echo form_label(lang('cms_settings_sidebar_back_all'));
                                                echo form_input(array('name'=>'layout_sidebar_background', 'id'=>'layout_sidebar_background'), set_value('layout_sidebar_background', get_setting('layout_sidebar_background')));
                                            echo '</div>';                                
                                        echo '</div>';
                                        echo '<div class="row">';
                                            echo '<h5>'.lang('cms_settings_sidebar_guides').'</h5>';
                                            echo '<div class="small-6 columns">';
                                                echo form_label(lang('cms_settings_sidebar_guides_font'));
                                                $options = array(''=>'','helvetica'=>'"Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif', 'verdana'=>'Verdana, Geneva, sans-serif','georgia'=>'Georgia, "Times New Roman", Times, serif','courier'=>'"Courier New", Courier, monospace','arial'=>'Arial, Helvetica, sans-serif','tahoma'=>'Tahoma, Geneva, sans-serif','trebuchet'=>'"Trebuchet MS", Arial, Helvetica, sans-serif','arialblack'=>'"Arial Black", Gadget, sans-serif','times'=>'"Times New Roman", Times, serif','palatino'=>'"Palatino Linotype", "Book Antiqua", Palatino, serif','lucida'=>'"Lucida Sans Unicode", "Lucida Grande", sans-serif','serif'=>'"MS Serif", "New York", serif','monaco'=>'"Lucida Console", Monaco, monospace','comic'=>'"Comic Sans MS", cursive',);
                                                echo form_dropdown('layout_sidebar_tabs_font', $options, set_value('"Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif', get_setting('layout_sidebar_tabs_font')));
                                            echo '</div>';
                                            echo '<div class="small-3 columns">';
                                                echo form_label(lang('cms_settings_sidebar_guides_size'));
                                                $options = array(''=>'','8px'=>'8px','9px'=>'9px','10px'=>'10px','11px'=>'11px','12px'=>'12px','14px'=>'14px','16px'=>'16px','20px'=>'20px','24px'=>'24px','28px'=>'28px','36px'=>'36px','48px'=>'48px',);
                                                echo form_dropdown('layout_sidebar_tabs_size', $options, set_value('14px', get_setting('layout_sidebar_tabs_size')));
                                            echo '</div>';
                                            echo '<div class="small-3 columns">';
                                                echo form_label(lang('cms_settings_sidebar_guides_color'));
                                                echo form_input(array('name'=>'layout_sidebar_tabs_color', 'id'=>'layout_sidebar_tabs_color'), set_value('layout_sidebar_tabs_color', get_setting('layout_sidebar_tabs_color')));
                                            echo '</div>';
                                        echo '</div>';
                                        echo '<div class="row">';
                                            echo '<h5>'.lang('cms_settings_sidebar_content').'</h5>';
                                            echo '<div class="small-6 columns">';
                                                echo form_label(lang('cms_settings_sidebar_content_font'));
                                                $options = array(''=>'','helvetica'=>'"Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif', 'verdana'=>'Verdana, Geneva, sans-serif','georgia'=>'Georgia, "Times New Roman", Times, serif','courier'=>'"Courier New", Courier, monospace','arial'=>'Arial, Helvetica, sans-serif','tahoma'=>'Tahoma, Geneva, sans-serif','trebuchet'=>'"Trebuchet MS", Arial, Helvetica, sans-serif','arialblack'=>'"Arial Black", Gadget, sans-serif','times'=>'"Times New Roman", Times, serif','palatino'=>'"Palatino Linotype", "Book Antiqua", Palatino, serif','lucida'=>'"Lucida Sans Unicode", "Lucida Grande", sans-serif','serif'=>'"MS Serif", "New York", serif','monaco'=>'"Lucida Console", Monaco, monospace','comic'=>'"Comic Sans MS", cursive',);
                                                echo form_dropdown('layout_sidebar_font', $options, set_value('"Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif', get_setting('layout_sidebar_font')));
                                            echo '</div>';
                                            echo '<div class="small-3 columns">';
                                                echo form_label(lang('cms_settings_sidebar_content_size'));
                                                $options = array(''=>'','8px'=>'8px','9px'=>'9px','10px'=>'10px','11px'=>'11px','12px'=>'12px','14px'=>'14px','16px'=>'16px','20px'=>'20px','24px'=>'24px','28px'=>'28px','36px'=>'36px','48px'=>'48px',);
                                                echo form_dropdown('layout_sidebar_size', $options, set_value('14px', get_setting('layout_sidebar_size')));
                                            echo '</div>';
                                            echo '<div class="small-3 columns">';
                                                echo form_label(lang('cms_settings_sidebar_content_colo'));
                                                echo form_input(array('name'=>'layout_sidebar_color', 'id'=>'layout_sidebar_color'), set_value('layout_sidebar_color', get_setting('layout_sidebar_color')));
                                            echo '</div>';
                                        echo '</div>';
                                    echo '</div>';
                                    echo '<div class="content" id="tab-5">';
                                        echo '<div class="row">';
                                            echo '<h5>'.lang('cms_settings_pages_background').'</h5>';
                                            echo '<div class="small-3 columns">';
                                                echo form_label(lang('cms_settings_pages_back_tit_color'));
                                                echo form_input(array('name'=>'layout_pages_title_background', 'id'=>'layout_pages_title_background'), set_value('layout_pages_title_background', get_setting('layout_pages_title_background')));
                                            echo '</div>';
                                            echo '<div class="small-3 columns left">';
                                                echo form_label(lang('cms_settings_pages_back_color'));
                                                echo form_input(array('name'=>'layout_pages_background', 'id'=>'layout_pages_background'), set_value('layout_pages_background', get_setting('layout_pages_background')));
                                            echo '</div>';                                
                                        echo '</div>';
                                        echo '<div class="row">';
                                            echo '<h5>'.lang('cms_settings_pages_titles').'</h5>';
                                            echo '<div class="small-6 columns">';
                                                echo form_label(lang('cms_settings_pages_font_title'));
                                                $options = array(''=>'','helvetica'=>'"Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif', 'verdana'=>'Verdana, Geneva, sans-serif','georgia'=>'Georgia, "Times New Roman", Times, serif','courier'=>'"Courier New", Courier, monospace','arial'=>'Arial, Helvetica, sans-serif','tahoma'=>'Tahoma, Geneva, sans-serif','trebuchet'=>'"Trebuchet MS", Arial, Helvetica, sans-serif','arialblack'=>'"Arial Black", Gadget, sans-serif','times'=>'"Times New Roman", Times, serif','palatino'=>'"Palatino Linotype", "Book Antiqua", Palatino, serif','lucida'=>'"Lucida Sans Unicode", "Lucida Grande", sans-serif','serif'=>'"MS Serif", "New York", serif','monaco'=>'"Lucida Console", Monaco, monospace','comic'=>'"Comic Sans MS", cursive',);
                                                echo form_dropdown('layout_pages_title_font', $options, set_value('"Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif', get_setting('layout_pages_title_font')));
                                            echo '</div>';
                                            echo '<div class="small-3 columns">';
                                                echo form_label(lang('cms_settings_pages_size_title'));
                                                $options = array(''=>'','8px'=>'8px','9px'=>'9px','10px'=>'10px','11px'=>'11px','12px'=>'12px','14px'=>'14px','16px'=>'16px','20px'=>'20px','24px'=>'24px','28px'=>'28px','36px'=>'36px','48px'=>'48px',);
                                                echo form_dropdown('layout_pages_title_size', $options, set_value('20px', get_setting('layout_pages_title_size')));
                                            echo '</div>';
                                            echo '<div class="small-3 columns">';
                                                echo form_label(lang('cms_settings_pages_texts'));
                                                echo form_input(array('name'=>'layout_pages_title_color', 'id'=>'layout_pages_title_color'), set_value('layout_pages_title_color', get_setting('layout_pages_title_color')));
                                            echo '</div>';
                                        echo '</div>';
                                        echo '<div class="row">';
                                            echo '<h5>'.lang('cms_settings_pages_texts_font').'</h5>';
                                            echo '<div class="small-6 columns">';
                                                echo form_label(lang('cms_settings_pages_texts_size'));
                                                $options = array(''=>'','helvetica'=>'"Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif', 'verdana'=>'Verdana, Geneva, sans-serif','georgia'=>'Georgia, "Times New Roman", Times, serif','courier'=>'"Courier New", Courier, monospace','arial'=>'Arial, Helvetica, sans-serif','tahoma'=>'Tahoma, Geneva, sans-serif','trebuchet'=>'"Trebuchet MS", Arial, Helvetica, sans-serif','arialblack'=>'"Arial Black", Gadget, sans-serif','times'=>'"Times New Roman", Times, serif','palatino'=>'"Palatino Linotype", "Book Antiqua", Palatino, serif','lucida'=>'"Lucida Sans Unicode", "Lucida Grande", sans-serif','serif'=>'"MS Serif", "New York", serif','monaco'=>'"Lucida Console", Monaco, monospace','comic'=>'"Comic Sans MS", cursive',);
                                                echo form_dropdown('layout_pages_text_font', $options, set_value('"Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif', get_setting('layout_pages_text_font')));
                                            echo '</div>';
                                            echo '<div class="small-3 columns">';
                                                echo form_label(lang('cms_settings_pages_texts_size'));
                                                $options = array(''=>'','8px'=>'8px','9px'=>'9px','10px'=>'10px','11px'=>'11px','12px'=>'12px','14px'=>'14px','16px'=>'16px','20px'=>'20px','24px'=>'24px','28px'=>'28px','36px'=>'36px','48px'=>'48px',);
                                                echo form_dropdown('layout_pages_text_size', $options, set_value('14px', get_setting('layout_pages_text_size')));
                                            echo '</div>';
                                            echo '<div class="small-3 columns">';
                                                echo form_label(lang('cms_settings_pages_texts_color'));
                                                echo form_input(array('name'=>'layout_pages_background', 'id'=>'layout_pages_background'), set_value('layout_pages_background', get_setting('layout_pages_background')));
                                            echo '</div>';
                                        echo '</div>';
                                    echo '</div>';
                                    echo '<div class="content" id="tab-6">';
                                        echo '<div class="row">';
                                            echo '<h5>'.lang('cms_settings_images').'</h5>';
                                            echo '<div class="small-4 columns">';
                                                echo form_label(lang('cms_settings_images_back_color'));
                                                echo form_input(array('name'=>'layout_images_background', 'id'=>'layout_images_background'), set_value('layout_images_background', get_setting('layout_images_background')));
                                            echo '</div>';
                                            echo '<div class="small-4 columns left">';
                                                echo form_label(lang('cms_settings_images_border_color'));
                                                echo form_input(array('name'=>'layout_images_border_color', 'id'=>'layout_images_border_color'), set_value('layout_images_border_color', get_setting('layout_images_border_color')));
                                            echo '</div>';
                                        echo '</div>';
                                    echo '</div>';
                                    echo '<div class="content" id="tab-7">';
                                        echo '<div class="row">';
                                            echo '<h5>'.lang('cms_settings_footer_background').'</h5>';
                                            echo '<div class="small-3 columns">';
                                                echo form_label(lang('cms_settings_footer_back_color'));
                                                echo form_input(array('name'=>'layout_footer_background', 'id'=>'layout_footer_background'), set_value('layout_footer_background', get_setting('layout_footer_background')));
                                            echo '</div>';
                                        echo '</div>';
                                        echo '<div class="row">';
                                            echo '<h5>'.lang('cms_settings_footer').'</h5>';
                                            echo '<div class="small-6 columns">';
                                                echo form_label(lang('cms_settings_footer_font'));
                                                $options = array(''=>'','helvetica'=>'"Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif', 'verdana'=>'Verdana, Geneva, sans-serif','georgia'=>'Georgia, "Times New Roman", Times, serif','courier'=>'"Courier New", Courier, monospace','arial'=>'Arial, Helvetica, sans-serif','tahoma'=>'Tahoma, Geneva, sans-serif','trebuchet'=>'"Trebuchet MS", Arial, Helvetica, sans-serif','arialblack'=>'"Arial Black", Gadget, sans-serif','times'=>'"Times New Roman", Times, serif','palatino'=>'"Palatino Linotype", "Book Antiqua", Palatino, serif','lucida'=>'"Lucida Sans Unicode", "Lucida Grande", sans-serif','serif'=>'"MS Serif", "New York", serif','monaco'=>'"Lucida Console", Monaco, monospace','comic'=>'"Comic Sans MS", cursive',);
                                                echo form_dropdown('layout_footer_font', $options, set_value('"Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif', get_setting('layout_footer_font')));
                                            echo '</div>';
                                            echo '<div class="small-3 columns">';
                                                echo form_label(lang('cms_settings_footer_size'));
                                                $options = array(''=>'','8px'=>'8px','9px'=>'9px','10px'=>'10px','11px'=>'11px','12px'=>'12px','14px'=>'14px','16px'=>'16px','20px'=>'20px','24px'=>'24px','28px'=>'28px','36px'=>'36px','48px'=>'48px',);
                                                echo form_dropdown('layout_footer_size', $options, set_value('14px', get_setting('layout_footer_size')));
                                            echo '</div>';
                                            echo '<div class="small-3 columns">';
                                                echo form_label(lang('cms_settings_footer_text_color'));
                                                echo form_input(array('name'=>'layout_footer_color', 'id'=>'layout_footer_color'), set_value('layout_footer_color', get_setting('layout_footer_color')));
                                            echo '</div>';
                                        echo '</div>';
                                    echo '</div>';
                                    echo '<div class="content" id="tab-8">';
                                        echo '<div class="row">';
                                            echo '<h5>'.lang('cms_settings_social').'</h5>';
                                        echo '</div>';
                                        echo '<div class="row">';
                                            echo '<div class="small-1 columns">';
                                                echo form_label('<i class="fa fa-envelope" style="font-size:40px; margin-top:22px;"></i>');
                                            echo '</div>';
                                            echo '<div class="small-11 columns">';
                                                echo form_label('E-mail');
                                                echo form_input(array('name'=>'layout_url_email'), set_value('layout_url_email', get_setting('layout_url_email')));
                                            echo '</div>';
                                        echo '</div>';
                                        echo '<div class="row">';
                                            echo '<div class="small-1 columns">';
                                                echo form_label('<i class="fa fa-facebook-square" style="font-size:40px; margin-top:22px;"></i>');
                                            echo '</div>';
                                            echo '<div class="small-11 columns">';
                                                echo form_label('URL facebook');
                                                echo form_input(array('name'=>'layout_url_facebook'), set_value('layout_url_facebook', get_setting('layout_url_facebook')));
                                            echo '</div>';
                                        echo '</div>';
                                        echo '<div class="row">';
                                            echo '<div class="small-1 columns">';
                                                echo form_label('<i class="fa fa-twitter-square" style="font-size:40px; margin-top:22px;"></i>');
                                            echo '</div>';
                                            echo '<div class="small-11 columns">';
                                                echo form_label('URL twitter');
                                                echo form_input(array('name'=>'layout_url_twitter'), set_value('layout_url_twitter', get_setting('layout_url_twitter')));
                                            echo '</div>';
                                        echo '</div>';
                                        echo '<div class="row">';
                                            echo '<div class="small-1 columns">';
                                                echo form_label('<i class="fa fa-google-plus" style="font-size:40px; margin-top:22px;"></i>');
                                            echo '</div>';
                                            echo '<div class="small-11 columns">';
                                                echo form_label('URL google plus');
                                                echo form_input(array('name'=>'layout_url_plus'), set_value('layout_url_plus', get_setting('layout_url_plus')));
                                            echo '</div>';
                                        echo '</div>';
                                        echo '<div class="row">';
                                            echo '<div class="small-1 columns">';
                                                echo form_label('<i class="fa fa-instagram" style="font-size:40px; margin-top:22px;"></i>');
                                            echo '</div>';
                                            echo '<div class="small-11 columns">';
                                                echo form_label('URL instagram');
                                                echo form_input(array('name'=>'layout_url_instagram'), set_value('layout_url_instagram', get_setting('layout_url_instagram')));
                                            echo '</div>';
                                        echo '</div>';
                                        echo '<div class="row">';
                                            echo '<div class="small-1 columns">';
                                                echo form_label('<i class="fa fa-dropbox" style="font-size:40px; margin-top:22px;"></i>');
                                            echo '</div>';
                                            echo '<div class="small-11 columns">';
                                                echo form_label('URL dropbox');
                                                echo form_input(array('name'=>'layout_url_dropbox'), set_value('layout_url_dropbox', get_setting('layout_url_dropbox')));
                                            echo '</div>';
                                        echo '</div>';
                                        echo '<div class="row">';
                                            echo '<div class="small-1 columns">';
                                                echo form_label('<i class="fa fa-github" style="font-size:40px; margin-top:22px;"></i>');
                                            echo '</div>';
                                            echo '<div class="small-11 columns">';
                                                echo form_label('URL github');
                                                echo form_input(array('name'=>'layout_url_github'), set_value('layout_url_github', get_setting('layout_url_github')));
                                            echo '</div>';
                                        echo '</div>';
                                        echo '<div class="row">';
                                            echo '<div class="small-1 columns">';
                                                echo form_label('<i class="fa fa-linkedin-square" style="font-size:40px; margin-top:22px;"></i>');
                                            echo '</div>';
                                            echo '<div class="small-11 columns">';
                                                echo form_label('URL linkedin');
                                                echo form_input(array('name'=>'layout_url_linkedin'), set_value('layout_url_linkedin', get_setting('layout_url_linkedin')));
                                            echo '</div>';
                                        echo '</div>';
                                        echo '<div class="row">';
                                            echo '<div class="small-1 columns">';
                                                echo form_label('<i class="fa fa-vimeo-square" style="font-size:40px; margin-top:22px;"></i>');
                                            echo '</div>';
                                            echo '<div class="small-11 columns">';
                                                echo form_label('URL vimeo');
                                                echo form_input(array('name'=>'layout_url_vimeo'), set_value('layout_url_vimeo', get_setting('layout_url_vimeo')));
                                            echo '</div>';
                                        echo '</div>';
                                        echo '<div class="row">';
                                            echo '<div class="small-1 columns">';
                                                echo form_label('<i class="fa fa-youtube-square" style="font-size:40px; margin-top:22px;"></i>');
                                            echo '</div>';
                                            echo '<div class="small-11 columns">';
                                                echo form_label('URL youtube');
                                                echo form_input(array('name'=>'layout_url_youtube'), set_value('layout_url_youtube', get_setting('layout_url_youtube')));
                                            echo '</div>';
                                        echo '</div>';
                                    echo '</div>';
                                    echo '<div class="content" id="tab-9">';
                                        echo '<div class="row">';
                                            echo '<h5>'.lang('cms_settings_css').'</h5>';
                                            echo '<div class="small-12 columns">';
                                                echo form_textarea(array('name'=>'layout_css', 'rows'=>'22', 'id'=>'layout_css', 'placeholder'=>lang('cms_settings_css_place')), set_value('layout_css', get_setting('layout_css')));
                                            echo '</div>';
                                        echo '</div>';
                                    echo '</div>';
                                echo '</div>';
                            echo '</div>';
                        echo '</div>';
                    endif;
                    echo '<div class="row">';
                        echo '<h5 class="small-12 columns">'.lang('permissions').'</h5>';
                        echo '<div class="small-12 columns">';
                            echo '<table id="users-settings-table-permissions">';
                                echo '<thead>';
                                    echo '<tr>';
                                        echo '<th class="small-2 collums">'.lang('permissions').'/'.lang('users_levels').'</th>';
                                            $query_userslevels = $this->userslevels->get_all()->result();
                                            foreach ($query_userslevels as $line):
                                                echo '<th class="small-1 collums">('.$line->userlevel_id.') '.$line->userlevel_name.'</th>';
                                            endforeach;
                                    echo '</tr>';
                                echo '</thead>';
                                echo '<tbody>';
                                    $alllabelspermissions = array(
                                        lang('cms_permissions_list_posts'),
                                        lang('cms_permissions_view_posts'),
                                        lang('cms_permissions_insert_posts'),
                                        lang('cms_permissions_update_posts'),
                                        lang('cms_permissions_delete_posts'),
                                        lang('cms_permissions_list_pages'),
                                        lang('cms_permissions_view_pages'),
                                        lang('cms_permissions_insert_pages'),
                                        lang('cms_permissions_update_pages'),
                                        lang('cms_permissions_delete_pages'),
                                        lang('cms_permissions_ger_medias'),
                                        lang('cms_permissions_ger_comments'),
                                        lang('cms_permissions_ger_themes'),
                                        lang('cms_permissions_ger_stats'),
                                        lang('cms_permissions_update_settings'),
                                        );
                                    $allpermissions = array(
                                        'perm_listposts_',
                                        'perm_viewposts_',
                                        'perm_insertposts_',
                                        'perm_updateposts_',
                                        'perm_deleteposts_',
                                        'perm_listpages_',
                                        'perm_viewpages_',
                                        'perm_insertpages_',
                                        'perm_updatepages_',
                                        'perm_deletepages_',
                                        'perm_medias_',
                                        'perm_comments_',
                                        'perm_themes_',
                                        'perm_stats_',
                                        'perm_contentssettings_'
                                    );
                                    $labelarray = 0;
                                    foreach ($allpermissions as $permission):
                                        echo '<tr>';
                                            $columnarray = 1;
                                            if ($permission):
                                                echo '<td>'.$alllabelspermissions[$labelarray].'</td>';
                                                $labelarray++;
                                                foreach ($query_userslevels as $line):
                                                    if ($permission == 'perm_ative_'):
                                                        echo get_permission($permission, $line->userlevel_id);
                                                    else:
                                                        echo get_permission($permission, $line->userlevel_id, TRUE);
                                                    endif;
                                                    $columnarray++;
                                                endforeach;
                                            else:
                                                echo '<td colspan="'.$columnarray.'"><strong>'.$alllabelspermissions[$labelarray].'</strong></td>';
                                                $labelarray++;
                                            endif;
                                        echo '</tr>';
                                    endforeach;
                                echo '</tbody>';
                            echo '</table>';
                        echo '</div>';
                    echo '</div>';
                    echo '<div class="small-12">';
                        echo form_submit(array('name'=>'save', 'class'=>'button small tiny right'), lang('cms_settings_save'));
                        echo form_submit(array('name'=>'clear', 'class'=>'button small alert tiny right deletereg'), lang('cms_settings_clear'));
                    echo '</div>';
                echo form_close();
            echo '</div>';
        echo '</div>';
        break;
}