language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: 5.6
    - php: hhvm

env:
  - DB=mysql
  - DB=pgsql
  - DB=sqlite

before_script:
  - composer self-update
  - composer install --no-progress
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  # enable php-fpm
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  # configure apache virtual hosts
  - sudo cp -f build/travis-ci-apache /etc/apache2/sites-available/default
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
  - sudo service apache2 restart
  # Set PyroCMS folder structure config
  - chmod 777 system/cms/config
  - chmod -R 777 system/cms/cache
  - chmod -R 777 addons
  - chmod -R 777 assets/cache
  - chmod -R 777 uploads
  - chmod 777 system/cms/modules/streams_core/models
  # DB driver specific setup
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'drop database if exists pyrocms; '; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database pyrocms; '; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'drop database if exists pyrocms;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'create database pyrocms;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'sqlite' ]; then touch build/test.sqlite; fi"
  - sh -c "if [ '$DB' = 'sqlite' ]; then chmod 666 build/test.sqlite; fi"
  - export PYRO_DB_HOST=127.0.0.1
  - export PYRO_WEB_HOST=127.0.0.1
  # Read in platform specific env config
  - echo build/travis/$DB.env
  - source build/travis/$DB.env

script:
  - ./system/vendor/bin/phing integration-test
