<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
switch ($screen) {
    case 'first':
        echo '<div class="row" id="dashboard-index">';
            echo '<div class="small-8 small-centered columns">';
                echo '<br><br><br><br>';
                echo '<div class="panel white">';
                    echo $this->lang->line('install_first');
                    echo form_open(current_url(), 'id="install-third-form-bd"');
                        echo '<div class="row">';
                            echo '<div class="small-6 columns">';
                                echo $this->lang->line('install_first_p');
                            echo '</div>'; 
                            echo '<div class="small-6 left columns">';
                                $lang_url = ($this->uri->segment(3) != NULL) ? $this->uri->segment(3) : 'English';
                                echo '<a href="#" data-dropdown="drop1" class="button columns tiny secondary dropdown">'.ucfirst($lang_url).'</a><br>';
                                    echo'<ul id="drop1" data-dropdown-content class="f-dropdown">';
                                        $languages = (directory_map('./compass-admin/language', TRUE));
                                        foreach ($languages as $lang):
                                            echo '<li><a href="'.base_url('install/index/'.$lang).'">'.ucfirst($lang).'</a></li>';
                                        endforeach;
                                    echo '</ul>';
                            echo '</div>';
                        echo '</div>';
                        echo '<div class="row">';
                            echo '<div class="small-12 columns">';
                                echo form_submit(array('name'=>'save', 'class'=>'button tiny'), $this->lang->line('install_first_submit'));
                            echo '</div>';
                        echo '</div>';
                    echo form_close();
                echo '</div>';
            echo '</div>';
        echo '</div>';
        break;
    case 'second':
        echo '<div class="row" id="dashboard-index">';
            echo '<div class="small-8 small-centered columns">';
                echo '<br><br>';
                echo '<div class="center"><div class="co-icon-m-compass"></div></div>';
                echo '<div class="panel white">';
                    echo $this->lang->line('install_second');
                    echo form_open(current_url(), 'id="install-third-form-bd"');
                        echo form_submit(array('name'=>'save', 'class'=>'button tiny'), $this->lang->line('install_second_submit'));
                    echo form_close();
                echo '</div>';
            echo '</div>';
        echo '</div>';
        break;
    case 'third':
        echo '<div class="row" id="dashboard-index">';
            echo '<div class="small-8 small-centered columns">';
                echo '<br><br>';
                echo '<div class="center"><div class="co-icon-m-compass"></div></div>';
                echo '<div class="panel white">';
                    errors_validating();
                    echo $this->lang->line('install_third');
                    echo form_open(current_url(), 'id="install-third-form-bd"');
                        echo '<div class="row">';
                            echo '<div class="small-3 columns"><strong>'.$this->lang->line('install_third_field_name').'</strong></div>';
                            echo '<div class="small-4 columns">';
                                echo form_input(array('name'=>'db_name'), 'compass');
                            echo '</div>';
                            echo '<div class="small-5 columns">'.$this->lang->line('install_third_small_name').'</div>';
                        echo '</div>';
                        echo '<div class="row">';
                            echo '<div class="small-3 columns"><strong>'.$this->lang->line('install_third_field_user').'</strong></div>';
                            echo '<div class="small-4 columns">';
                                echo form_input(array('name'=>'db_user'), 'root');
                            echo '</div>';
                            echo '<div class="small-5 columns">'.$this->lang->line('install_third_small_user').'</div>';
                        echo '</div>';
                        echo '<div class="row">';
                            echo '<div class="small-3 columns"><strong>'.$this->lang->line('install_third_field_pass').'</strong></div>';
                            echo '<div class="small-4 columns">';
                                echo form_input(array('name'=>'db_pass'));
                            echo '</div>';
                            echo '<div class="small-5 columns">'.$this->lang->line('install_third_small_pass').'</div>';
                        echo '</div>';
                        echo '<div class="row">';
                            echo '<div class="small-3 columns"><strong>'.$this->lang->line('install_third_field_server').'</strong></div>';
                            echo '<div class="small-4 columns">';
                                echo form_input(array('name'=>'db_server'), 'localhost');
                            echo '</div>';
                            echo '<div class="small-5 columns">'.$this->lang->line('install_third_small_server').'</div>';
                        echo '</div>';
                        echo '<div class="row">';
                            echo '<div class="small-12 columns">';
                                echo form_submit(array('name'=>'install', 'class'=>'button tiny'), $this->lang->line('install_third_submit'));
                            echo '</div>';
                        echo '</div>';
                    echo form_close();
                echo '</div>';
            echo '</div>';
        echo '</div>';
        break;
    case 'fourth':
        echo '<div class="row" id="dashboard-index">';
            echo '<div class="small-6 small-centered columns">';
                echo '<br><br>';
                echo '<div class="center"><div class="co-icon-m-compass"></div></div>';
                echo '<div class="panel white">';
                    echo $this->lang->line('install_fourth');
                    echo form_open(current_url(), 'id="install-third-form-bd"');
                        echo form_submit(array('name'=>'install', 'class'=>'button tiny'), $this->lang->line('install_fourth_submit'));
                    echo form_close();
                echo '</div>';
            echo '</div>';
        echo '</div>';
        break;
    case 'fifth':
        echo '<div class="row" id="dashboard-index">';
            echo '<div class="small-8 small-centered columns">';
                echo '<br><br>';
                echo '<div class="center"><div class="co-icon-m-compass"></div></div>';
                echo '<div class="panel white">';
                    errors_validating();
                    echo $this->lang->line('install_fifth').' '.anchor('install/readme', 'ReadMe').' '.$this->lang->line('install_fifth_2');
                    echo form_open(current_url(), 'id="install-third-form-bd"');
                        echo '<div class="row">';
                            echo '<div class="small-3 columns">'.$this->lang->line('install_fifth_title').'</div>';
                            echo '<div class="small-6 columns end">';
                                echo form_input(array('name'=>'title'));
                            echo '</div>';
                        echo '</div>';
                        echo '<div class="row">';
                            echo '<div class="small-3 columns">'.$this->lang->line('install_fifth_description').'</div>';
                            echo '<div class="small-6 columns end">';
                                echo form_textarea(array('name'=>'description', 'rows'=>'4'));
                            echo '</div>';
                        echo '</div>';
                        echo '<div class="row">';
                            echo '<div class="small-3 columns">'.$this->lang->line('install_fifth_user').'</div>';
                            echo '<div class="small-6 columns end">';
                                echo form_input(array('name'=>'user'));
                            echo '</div>';
                        echo '</div>';
                        echo '<div class="row">';
                            echo '<div class="small-3 columns">'.$this->lang->line('install_fifth_pass').$this->lang->line('install_fifth_pass_small').'</div>';
                            echo '<div class="small-6 columns end">';
                                echo form_input(array('name'=>'pass'));
                                echo form_input(array('name'=>'pass2'));
                            echo '</div>';
                        echo '</div>';
                        echo '<div class="row">';
                            echo '<div class="small-3 columns">'.$this->lang->line('install_fifth_email').$this->lang->line('install_fifth_email_small').'</div>';
                            echo '<div class="small-6 columns end">';
                                echo form_input(array('name'=>'email'));
                            echo '</div>';
                        echo '</div>';
                        echo $this->lang->line('install_fifth_3');
                        echo '<div class="row">';
                            echo '<div class="small-12 columns end">';
                                echo '<table id="tools-modules-table-list" class="small-12">';
                                    echo '<thead>';
                                        echo '<tr>';
                                            echo '<th class="">#</th>';
                                            echo '<th class="small-3 collums">'.lang('modules_name').'</th>';
                                            echo '<th class="small-9 collums">'.lang('modules_description').'</th>';
                                        echo '</tr>';
                                    echo '</thead>';
                                    echo '<tbody>';
                                        $themes_directorys = directory_map('./compass-admin/modules/', TRUE);
                                        if (in_array('index.html', $themes_directorys)) unset($themes_directorys[array_search('index.html',$themes_directorys)]);
                                        foreach ($themes_directorys as $name_theme_directory):
                                            $theme_directory_details = directory_map('./compass-admin/modules/'.$name_theme_directory, TRUE);
                                            if (in_array('readme.txt', $theme_directory_details)):
                                                echo '<tr class="table-order">';
                                                    //abrir o the_file em leitura
                                                    $the_file = './compass-admin/modules/'.$name_theme_directory.'/readme.txt';
                                                    //transformamos as quebras de linha em etiquetas <br>
                                                    //Por meio do fopen o the_file é carregado, o fread ler o the_file e identifica seu tamanho por meio do filesize, o nl2br transforma as quebras de linhas em <br>.
                                                    $the_text = nl2br(fread(fopen($the_file,'r'), filesize($the_file)));
                                                    //Procura na variável $the_text o trecho que inicia na posição do caractere inicial do elemento 'Contributors: ' dentro da variável $the_text e conclui na posição do caractere inicial da primeira ocorrência do elemento '<br' a partir da ocorrencia do elemento 'Contributors: ', na variável the_text. O str_replace apaga o título do módulo
                                                    $the_module_name = str_replace('Module Name: ', '', substr($the_text, strripos($the_text, 'Module Name: '), strpos(substr($the_text, strripos($the_text, 'Module Name: ')), '<br')));
                                                    $the_module_url = str_replace('Module URI: ', '', substr($the_text, strripos($the_text, 'Module URI: '), strpos(substr($the_text, strripos($the_text, 'Module URI: ')), '<br')));
                                                    $the_module_description = str_replace('Description: ', '', substr($the_text, strripos($the_text, 'Description: '), strpos(substr($the_text, strripos($the_text, 'Description: ')), '<br')));
                                                    $the_module_author = str_replace('Author: ', '', substr($the_text, strripos($the_text, 'Author: '), strpos(substr($the_text, strripos($the_text, 'Author: ')), '<br')));
                                                    $the_module_author_url = str_replace('Author URI: ', '', substr($the_text, strripos($the_text, 'Author URI: '), strpos(substr($the_text, strripos($the_text, 'Author URI: ')), '<br')));
                                                    $the_module_version = str_replace('Version: ', '', substr($the_text, strripos($the_text, 'Version: '), strpos(substr($the_text, strripos($the_text, 'Version: ')), '<br')));
                                                    printf('<td>%s</td>', form_checkbox(array('name'=>'module_'.$name_theme_directory, 'id'=>'module_'.$name_theme_directory), '1', ($name_theme_directory == 'cms' || $name_theme_directory == 'books') ? TRUE : FALSE));
                                                    printf('<td>%s</td>', form_label($the_module_name, 'module_'.$name_theme_directory));
                                                    printf('<td style="max-height:200px !important;">%s</td>', $the_module_description.' <a href="#" data-reveal-id="Modal-'.$name_theme_directory.'">'.lang('modules_more').'</a><br>'.lang('modules_version').' <strong>'.$the_module_version.'</strong> | '.lang('modules_by').' '.anchor($the_module_author_url, $the_module_author).' | '.anchor($the_module_url, lang('modules_view_url'))
                                                        );
                                                    echo '<div id="Modal-'.$name_theme_directory.'" class="reveal-modal" data-reveal><h3>'.ucfirst($name_theme_directory).'/readme.txt</h3><p>'.$the_text.'</p><a class="close-reveal-modal">&#215;</a></div>';
                                                echo '</tr>';
                                            endif;
                                        endforeach;
                                    echo '</tbody>';
                                echo '</table>';
                            echo '</div>';
                        echo '</div>';
                        /*echo '<div class="row">';
                            echo '<div class="small-4 medium-3 large-2 columns center">';
                                echo form_label('<div class="co-icon-m-compass"></div> <br>Core © Content Manager Press as System', 'module_books');
                                echo form_checkbox(array('name'=>'module_books', 'id'=>'module_books', 'disabled'=>'disabled'), '1', TRUE);
                            echo '</div>';
                            echo '<div class="small-4 medium-3 large-2 columns center end">';
                                echo form_label('<div class="co-icon-m-cms"></div> <br> CMS © Content Manager Press as System', 'module_cms');
                                echo form_checkbox(array('name'=>'module_cms', 'id'=>'module_cms'), '1', TRUE);
                            echo '</div>';
                            echo '<div class="small-4 medium-3 large-2 columns center end">';
                                echo form_label('<div class="co-icon-m-books"></div> <br> Books © Content Manager Press as System', 'module_books');
                                echo form_checkbox(array('name'=>'module_books', 'id'=>'module_books'), '1', FALSE);
                            echo '</div>';
                            echo '<div class="small-4 medium-3 large-2 columns center end">';
                                echo form_label('<div class="co-icon-m-journal"></div> <br> Journal © Content Manager Press as System', 'module_journal');
                                echo form_checkbox(array('name'=>'module_journal', 'id'=>'module_journal', 'disabled'=>'disabled'), '1', FALSE);
                            echo '</div>';
                            echo '<div class="small-4 medium-3 large-2 columns center end">';
                                echo form_label('<div class="co-icon-m-eventus"></div> <br> Eventus © Content Manager Press as System', 'module_eventus');
                                echo form_checkbox(array('name'=>'module_eventus', 'id'=>'module_eventus', 'disabled'=>'disabled'), '1', FALSE);
                            echo '</div>';
                            echo '<div class="small-4 medium-3 large-2 columns center end">';
                                echo form_label('<div class="co-icon-m-helpdesck"></div> <br> Helpdesck © Content Manager Press as System', 'module_helpdesk');
                                echo form_checkbox(array('name'=>'module_helpdesk', 'id'=>'module_helpdesk', 'disabled'=>'disabled'), '1', FALSE);
                            echo '</div>';
                        echo '</div>';*/
                        echo '<div class="row">';
                            echo '<div class="small-12 columns">';
                                echo form_submit(array('name'=>'install', 'class'=>'button tiny'), $this->lang->line('install_fifth_submit'));
                            echo '</div>';
                        echo '</div>';
                    echo form_close();
                echo '</div>';
            echo '</div>';
        echo '</div>';
        break;
    case 'sixth':
        echo '<div class="row" id="dashboard-index">';
            echo '<div class="small-6 small-centered columns">';
                echo '<br><br>';
                echo '<div class="center"><div class="co-icon-m-compass"></div></div>';
                echo '<div class="panel white">';
                    echo $this->lang->line('install_sixth');
                    echo '<br>';
                    echo '<div class="row">';
                        echo '<div class="small-3 columns"><strong>'.$this->lang->line('install_sixth_user').'</strong></div>';
                        echo '<div class="small-9 columns">'.$this->users->get_by_id(1)->row()->user_username.'</div>';
                    echo '</div>';
                    echo '<br><br>';
                    echo '<div class="row">';
                        echo '<div class="small-3 columns"><strong>'.$this->lang->line('install_sixth_pass').'</strong></div>';
                        echo '<div class="small-9 columns"><i>'.$this->lang->line('install_sixth_pass_r').'</i></div>';
                    echo '</div>';
                    echo '<br><br>';
                    echo '<p>'.anchor('login', 'Log in', array('class'=>'button tiny')).'</p>';
                echo '</div>';
            echo '</div>';
        echo '</div>';
        break;
    case 'readme':
        echo '<div class="row" id="dashboard-index">';
            echo '<div class="small-8 small-centered columns">';
                echo '<br><br>';
                echo '<div class="center"><div class="co-icon-m-compass"></div></div>';
                echo '<div class="panel white">';
                echo $this->lang->line('core_install_readme');
                echo form_open(current_url(), 'id="install-third-form-bd"');
                    echo form_submit(array('name'=>'save', 'class'=>'button tiny'), $this->lang->line('install_second_submit'));
                echo form_close();
                echo '</div>';
            echo '</div>';
        echo '</div>';
        break;
}