<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
switch ($screen) {
	case 'catalog':
		echo '<div id="books-index" class="row">';
            echo '<div class="small-5 columns">';
                echo '<h3 class="left">'.lang('books').'</h3>';
                echo anchor('books/catalog/insert', lang('books_insert'), 'class="addimg button button-tiny secondary radius space-v-medium space-h-small"');
            echo '</div>';
            echo '<div class="small-3 columns">';
                    $query_tags_list = $this->books->get_all()->result();
                    $all_tags = NULL;
                    foreach ($query_tags_list as $line):
                        if ($line->book_tags != NULL):
                            $all_tags .= $line->book_tags.',';
                        endif;
                    endforeach;
                    $all_tags = array_unique(explode(',', rtrim($all_tags, ",")));
                $title_select = ($this->uri->segment($config['filter_key_segment']) == 'filter_tag') ? lang('books_with_tags').' '.ucfirst($this->uri->segment($config['filter_value_segment'])) : lang('books_show_all');
                echo '<a href="#" data-dropdown="drop1" class="tiny button secondary dropdown expand">'.$title_select.'</a>';
                echo '<ul id="drop1" data-dropdown-content class="f-dropdown">';
                    foreach ($all_tags as $line):
                        echo '<li><a href="'.base_url('books/catalog/index/0/orderby/book_title/order/desc/filter_tag').'/'.str_replace(' ', '-', $line).'">'.ucfirst($line).'</a></li>';
                    endforeach;
                echo '</ul>';
            echo '</div>';
            echo '<div class="small-4 columns">';
                echo form_open(current_url(), 'id="books-index-form-search"');
                    echo '<div class="row">';
                        echo '<div class="row collapse">';
                            echo '<div class="small-7 columns">';
                                echo form_input(array('name'=>'search_for', 'placeholder'=>lang('core_search')), set_value('search', ($this->uri->segment($config['filter_key_segment']) == 'search') ? $this->uri->segment($config['filter_value_segment']) : NULL));
                            echo '</div>';
                            echo '<div class="small-5 columns">';
                                echo form_submit(array('name'=>'search', 'class'=>'small-11 button secondary tiny', 'title'=>lang('book_search')), lang('book_search'));
                            echo '</div>';
                        echo '</div>';
                    echo '</div>';
                echo form_close();
            echo '</div>';
        echo '</div>';
        echo '<table id="users-index-table-list" class="small-12 columns">';
            echo '<thead>';
                echo '<tr class="table-order">';
                    echo '<th class="small-1">'.lang('books_field_cover').'</th>';
                    echo '<th class="small-5">'.get_th_orderby(lang('books_field_title'), 'book_title', $config).'</th>';
                    echo '<th class="small-3">'.lang('books_field_tags').'</th>';
                    echo '<th class="small-3">'.lang('books_field_reference').'</th>';
                echo '</tr>';
            echo '</thead>';
            echo '<tbody>';
                $query_numrows = 0;
                foreach (get_query($config)->result() as $line):
                    echo '<tr>';
                		printf('<td>%s</td>', thumb($line->book_cover, 150, 150));
                		printf('<td class="table-operations"><h5>%s</h5><strong>'.lang('books_field_author').': </strong>%s<br><strong>'.lang('books_field_register').': </strong>%s<br><strong>'.lang('books_field_publication').': </strong>%s. Ed. %s: %s, %s, %sp.<br>%s %s %s</td>', 
							$line->book_title, $line->book_author, $line->book_register, $line->book_edition, $line->book_publisher, $line->book_city_publisher, $line->book_year_publisher, $line->book_number_pages,
							(access('perm_booksupdate_', NULL, TRUE)) ? anchor("books/catalog/update/$line->book_id", lang('core_update'), array('class'=>'table-action table-action-first update')) : NULL, 
							(access('perm_booksdelete_', NULL, TRUE)) ? anchor("books/catalog/delete/$line->book_id", lang('core_delete'), array('class'=>'table-action delete deletereg')): NULL,
							(access('perm_booksview_', NULL, TRUE)) ? anchor_popup("books/catalog/details/$line->book_id", lang('core_details'), array('class'=>'table-action update')) : NULL
							);
                		$tags = array();
                        if ($line->book_tags != NULL):
                            $query_tags = explode(',', $line->book_tags);
                            foreach ($query_tags as $line_tag):
                                $tags[] = anchor("books/catalog/index/0/orderby/book_title/order/desc/filter_tag/".str_replace(' ', '-', $line_tag), ucfirst($line_tag));
                            endforeach;
                        endif;
                        printf('<td>%s</td>', join(", ", $tags));
                        $reference = str_replace("[title]", $line->book_title, get_setting('books_reference_model'));
                        $reference = str_replace("[author]", $line->book_author, $reference);
                        $reference = str_replace("[tags]", $line->book_tags, $reference);
                        $reference = str_replace("[language]", $line->book_language, $reference);
                        $reference = str_replace("[keywords]", $line->book_keywords, $reference);
                        $reference = str_replace("[edition]", $line->book_edition, $reference);
                        $reference = str_replace("[publisher]", $line->book_publisher, $reference);
                        $reference = str_replace("[city]", $line->book_city_publisher, $reference);
                        $reference = str_replace("[year]", $line->book_year_publisher, $reference);
                        $reference = str_replace("[pages]", $line->book_number_pages, $reference);
                        $reference = str_replace("[isbn]", $line->book_isbn, $reference);
                        $reference = str_replace("[cdd]", $line->book_cdd, $reference);
                        $reference = str_replace("[cdu]", $line->book_cdu, $reference);
                        $reference = str_replace("[synopsis]", $line->book_synopsis, $reference);
                        printf('<td>%s</td>', $reference);
                        echo '<td class="table-operations"> ', '';
					echo '</tr>';
                    $query_numrows++;
                endforeach;
            echo '</tbody>';
            echo '<thead>';
                echo '<tr class="table-order">';
                    echo '<th class="small-1">'.lang('books_field_cover').'</th>';
                    echo '<th class="small-5">'.get_th_orderby(lang('books_field_title'), 'book_title', $config).'</th>';
                    echo '<th class="small-3">'.lang('books_field_tags').'</th>';
                    echo '<th class="small-3">'.lang('books_field_reference').'</th>';
                echo '</tr>';
            echo '</thead>';
        echo '</table>';
        echo '<div class="row">';
            echo '<div class="small-12 medium-6 large-4 columns">';
                $rows = get_query($config, 'all')->num_rows();
                echo "<small>".lang('core_showing')." ".$query_numrows." - $rows ".lang('core_registers')."</small>";
            echo '</div>';
            echo '<div class="small-12 medium-6 large-8 columns">';
                get_pagination($config);
            echo '</div>';
        echo '</div>';
		break;
	case 'insert':
        echo '<h3>Inserir novo Evento</h3>';
		echo form_open_multipart(current_url());
			echo '<h5>Sobre o Evento</h5>';
			echo '<div class="row">';
				echo '<div class="small-12 large-6 columns">';
					echo '<div class="row">';
						echo '<div class="small-12 columns">';
							echo form_label('Nome do Evento');
							echo form_input(array('name'=>'event_name', 'placeholder'=>'Nome do evento'), set_value('event_name'), 'autofocus');
						echo '</div>';
						echo '<div class="small-12 columns">';
							echo form_label('E-mail para contato');
							echo form_input(array('name'=>'event_email', 'placeholder'=>'E-mail para contato'), set_value('event_email'));
						echo '</div>';
						echo '<div class="small-12 columns">';
							echo '<div class="row">';
								echo '<div class="small-6 columns">';
									echo form_label('Data de início');
									echo form_input(array('name'=>'event_date_on', 'placeholder'=>'Data de início', 'class'=>'datetimepicker'), set_value('event_date_on'));
								echo '</div>';
								echo '<div class="small-6 columns">';
									echo form_label('Data de conclusão');
									echo form_input(array('name'=>'event_date_off', 'placeholder'=>'Data de conclusão', 'class'=>'datetimepicker'), set_value('event_date_off'));
								echo '</div>';
							echo '</div>';
						echo '</div>';
					echo '</div>';
				echo '</div>';
				echo '<div class="small-12 large-6 columns">';
					echo form_label('Descrição');
					echo form_textarea(array('name'=>'event_description', 'rows'=>'5', 'placeholder'=>'Descrição', 'class'=>'tinymce'), set_value('event_description'));
				echo '</div>';
			echo '</div>';
			echo '<h5>Local do Evento</h5>';
			echo '<div class="row">';
				echo '<div class="small-12 medium-10 large-8 columns and">';
					echo form_label('Local');
					echo form_input(array('name'=>'event_locale', 'placeholder'=>'Local'), set_value('event_locale'));
				echo '</div>';
			echo '</div>';
			echo '<div class="row">';
				echo '<div class="small-8 medium-6 large-4 columns">';
					echo form_label('CEP');
					echo form_input(array('name'=>'event_cep', 'placeholder'=>'CEP'), set_value('event_cep'));
				echo '</div>';
			echo '</div>';
			echo '<div class="row">';
				echo '<div class="small-12 medium-10 large-8 columns">';
					echo form_label('Endereço');
					echo form_input(array('name'=>'event_adress', 'placeholder'=>'Endereço'), set_value('event_adress'));
				echo '</div>';
			echo '</div>';
			echo '<div class="row">';
				echo '<div class="small-8 medium-6 large-4 columns">';
					echo form_label('Bairro');
					echo form_input(array('name'=>'event_district', 'placeholder'=>'Bairro'), set_value('event_district'));
				echo '</div>';
			echo '</div>';
			echo '<div class="row">';
				echo '<div class="small-8 medium-6 large-4 columns">';
					echo form_label('Cidade');
					echo form_input(array('name'=>'event_city', 'placeholder'=>'Cidade'), set_value('event_city'));
				echo '</div>';
			echo '</div>';
			echo '<div class="row">';
				echo '<div class="small-8 medium-6 large-4 columns">';
					echo form_label('Estado');
					echo form_input(array('name'=>'event_state', 'placeholder'=>'Estado'), set_value('event_state'));
				echo '</div>';
			echo '</div>';
			echo '<h5>Inscrições</h5>';
			echo '<div class="row">';
				echo '<div class="small-12 columns">';
					echo '<table id="">';
			            echo '<thead>';
			                echo '<tr>';
			                    echo '<th class=""><div>Lote</div></th>';
			                    echo '<th class="small-3">Nome</th>';
			                    echo '<th class="small-5">Descrição</th>';
			                    echo '<th class="small-2">Preço</th>';
			                    echo '<th class="small-2">Quantidade</th>';
			                echo '</tr>';
			            echo '</thead>';
			            echo '<tbody>';
			                    echo '<tr>';
			                		echo '<td>1</td>';
			                		echo '<td>'.form_input(array('name'=>'event_lot_1_name', 'placeholder'=>'Nome do lote', 'style'=>'margin:0px !important; font-size:20px; border:none;'), set_value('event_lot_1_name', 'Gratis')).'</td>';
			                		echo '<td>'.form_textarea(array('name'=>'event_lot_1_description', 'rows'=>'2', 'placeholder'=>'Descrição', 'style'=>'margin:0px !important; border:none;'), set_value('event_lot_1_description', 'Nenhuma quantia será cobrada para inscrições neste lote.')).'</td>';
			                		echo '<td>'.form_input(array('name'=>'event_lot_1_price', 'placeholder'=>'Preço', 'style'=>'margin:0px !important; font-size:20px; border:none;'), set_value('event_lot_1_price', '00,00')).'</td>';
			                		echo '<td>'.form_input(array('name'=>'event_lot_1_quantity', 'placeholder'=>'Quantidade', 'style'=>'margin:0px !important; font-size:20px; border:none;'), set_value('event_lot_1_quantity', '1000')).'</td>';
								echo '</tr>';
								echo '<tr>';
			                		echo '<td>2</td>';
			                		echo '<td>'.form_input(array('name'=>'event_lot_2_name', 'placeholder'=>'Nome do lote', 'style'=>'margin:0px !important; font-size:20px; border:none;'), set_value('event_lot_2_name')).'</td>';
			                		echo '<td>'.form_textarea(array('name'=>'event_lot_2_description', 'rows'=>'2', 'placeholder'=>'Descrição', 'style'=>'margin:0px !important; border:none;'), set_value('event_lot_2_description')).'</td>';
			                		echo '<td>'.form_input(array('name'=>'event_lot_2_price', 'placeholder'=>'Preço', 'style'=>'margin:0px !important; font-size:20px; border:none;'), set_value('event_lot_2_price')).'</td>';
			                		echo '<td>'.form_input(array('name'=>'event_lot_2_quantity', 'placeholder'=>'Quantidade', 'style'=>'margin:0px !important; font-size:20px; border:none;'), set_value('event_lot_2_quantity')).'</td>';
								echo '</tr>';
								echo '<tr>';
			                		echo '<td>3</td>';
			                		echo '<td>'.form_input(array('name'=>'event_lot_3_name', 'placeholder'=>'Nome do lote', 'style'=>'margin:0px !important; font-size:20px; border:none;'), set_value('event_lot_3_name')).'</td>';
			                		echo '<td>'.form_textarea(array('name'=>'event_lot_3_description', 'rows'=>'2', 'placeholder'=>'Descrição', 'style'=>'margin:0px !important; border:none;'), set_value('event_lot_3_description')).'</td>';
			                		echo '<td>'.form_input(array('name'=>'event_lot_3_price', 'placeholder'=>'Preço', 'style'=>'margin:0px !important; font-size:20px; border:none;'), set_value('event_lot_3_price')).'</td>';
			                		echo '<td>'.form_input(array('name'=>'event_lot_3_quantity', 'placeholder'=>'Quantidade', 'style'=>'margin:0px !important; font-size:20px; border:none;'), set_value('event_lot_3_quantity')).'</td>';
								echo '</tr>';
								echo '<tr>';
			                		echo '<td>4</td>';
			                		echo '<td>'.form_input(array('name'=>'event_lot_4_name', 'placeholder'=>'Nome do lote', 'style'=>'margin:0px !important; font-size:20px; border:none;'), set_value('event_lot_4_name')).'</td>';
			                		echo '<td>'.form_textarea(array('name'=>'event_lot_4_description', 'rows'=>'2', 'placeholder'=>'Descrição', 'style'=>'margin:0px !important; border:none;'), set_value('event_lot_4_description')).'</td>';
			                		echo '<td>'.form_input(array('name'=>'event_lot_4_price', 'placeholder'=>'Preço', 'style'=>'margin:0px !important; font-size:20px; border:none;'), set_value('event_lot_4_price')).'</td>';
			                		echo '<td>'.form_input(array('name'=>'event_lot_4_quantity', 'placeholder'=>'Quantidade', 'style'=>'margin:0px !important; font-size:20px; border:none;'), set_value('event_lot_4_quantity')).'</td>';
								echo '</tr>';
								echo '<tr>';
			                		echo '<td>5</td>';
			                		echo '<td>'.form_input(array('name'=>'event_lot_5_name', 'placeholder'=>'Nome do lote', 'style'=>'margin:0px !important; font-size:20px; border:none;'), set_value('event_lot_5_name')).'</td>';
			                		echo '<td>'.form_textarea(array('name'=>'event_lot_5_description', 'rows'=>'2', 'placeholder'=>'Descrição', 'style'=>'margin:0px !important; border:none;'), set_value('event_lot_5_description')).'</td>';
			                		echo '<td>'.form_input(array('name'=>'event_lot_5_price', 'placeholder'=>'Preço', 'style'=>'margin:0px !important; font-size:20px; border:none;'), set_value('event_lot_5_price')).'</td>';
			                		echo '<td>'.form_input(array('name'=>'event_lot_5_quantity', 'placeholder'=>'Quantidade', 'style'=>'margin:0px !important; font-size:20px; border:none;'), set_value('event_lot_5_quantity')).'</td>';
								echo '</tr>';
			            echo '</tbody>';
			        echo '</table>';
				echo '</div>';
			echo '</div>';


			echo form_submit(array('name'=>'save', 'class'=>'button radius tiny'), lang('core_save'));
			echo anchor('books', lang('core_cancel'), array('class'=>'alertlink'));
		echo form_close();
		break;
	case 'update':
        $query = $this->books->get_by_id($this->uri->segment(4))->row();
        echo '<h3>'.lang('books_update').'</h3>';
		echo form_open_multipart(current_url(), array('class'=>'custom'));
			echo '<div class="row">';
				echo '<div class="small-2 columns">';
					echo form_label(lang('books_field_cover'));
					echo thumb($query->book_cover, 200, 200);
					if ($query->book_cover != NULL):
						echo form_submit(array('name'=>'remove_cover', 'class'=>'button tiny button-tiny columns'), lang('books_remove_cover'));
					else:
						echo form_upload(array('name'=>'book_cover'), set_value('book_cover'));
						echo form_submit(array('name'=>'save_cover', 'class'=>'button tiny button-tiny columns'), lang('books_send_cover'));
					endif;
				echo '</div>';
				echo '<div class="small-10 columns">';
					echo '<div class="row">';
						echo '<div class="small-12 columns">';
							echo form_label(lang('books_field_title'));
							echo form_input(array('name'=>'book_title', 'placeholder'=>lang('books_field_title')), set_value('book_title', $query->book_title), 'autofocus');
						echo '</div>';
					echo '</div>';
					echo '<div class="row">';
						echo '<div class="small-3 columns">';
							echo form_label(lang('books_field_register'));
							echo form_input(array('name'=>'book_register', 'placeholder'=>lang('books_field_register'), 'disabled'=>'disabled'), set_value('book_register', $query->book_register));
						echo '</div>';
						echo '<div class="small-9 columns">';
							echo form_label(lang('books_field_author'));
							echo form_input(array('name'=>'book_author', 'placeholder'=>lang('books_field_author')), set_value('book_author', $query->book_author));
						echo '</div>';
					echo '</div>';
				echo '</div>';
			echo '</div>';
			echo '<div class="row">';
				echo '<div class="small-5 columns">';
					echo form_label(lang('books_field_tags'));
					echo form_input(array('name'=>'book_tags', 'placeholder'=>lang('books_field_tags'), 'id'=>'tags'), set_value('book_tags', $query->book_tags));
				echo '</div>';
				echo '<div class="small-3 columns">';
					echo form_label(lang('books_field_language'));
					echo form_input(array('name'=>'book_language', 'placeholder'=>lang('books_field_language')), set_value('book_language', $query->book_language));
				echo '</div>';
				echo '<div class="small-4 columns">';
					echo form_label(lang('books_field_keywords'));
					echo form_input(array('name'=>'book_keywords', 'placeholder'=>lang('books_field_keywords')), set_value('book_keywords', $query->book_keywords));
				echo '</div>';
			echo '</div>';
			echo '<div class="row">';
				echo '<div class="small-2 columns">';
					echo form_label(lang('books_field_edition'));
					echo form_input(array('name'=>'book_edition', 'placeholder'=>lang('books_field_edition')), set_value('book_edition', $query->book_edition));
				echo '</div>';
				echo '<div class="small-3 columns">';
					echo form_label(lang('books_field_publisher'));
					echo form_input(array('name'=>'book_publisher', 'placeholder'=>lang('books_field_publisher')), set_value('book_publisher', $query->book_publisher));
				echo '</div>';
				echo '<div class="small-3 columns">';
					echo form_label(lang('books_field_city'));
					echo form_input(array('name'=>'book_city_publisher', 'placeholder'=>lang('books_field_city')), set_value('book_city_publisher', $query->book_city_publisher));
				echo '</div>';
				echo '<div class="small-2 columns">';
					echo form_label(lang('books_field_year'));
					echo form_input(array('name'=>'book_year_publisher', 'placeholder'=>lang('books_field_year')), set_value('book_year_publisher', $query->book_year_publisher));
				echo '</div>';
				echo '<div class="small-2 columns">';
					echo form_label(lang('books_field_n_pages'));
					echo form_input(array('name'=>'book_number_pages', 'placeholder'=>lang('books_field_n_pages')), set_value('book_number_pages', $query->book_number_pages));
				echo '</div>';
			echo '</div>';
			echo '<div class="row">';
				echo '<div class="small-6 columns">';
					echo '<div class="row">';
						echo '<div class="small-4 columns">';
							echo form_label(lang('books_field_isbn'));
							echo form_input(array('name'=>'book_isbn', 'placeholder'=>lang('books_field_isbn')), set_value('book_isbn', $query->book_isbn));
						echo '</div>';
						echo '<div class="small-4 columns">';
							echo form_label(lang('books_field_cdd'));
							echo form_input(array('name'=>'book_cdd', 'placeholder'=>lang('books_field_cdd')), set_value('book_cdd', $query->book_cdd));
						echo '</div>';
						echo '<div class="small-4 columns">';
							echo form_label(lang('books_field_cdu'));
							echo form_input(array('name'=>'book_cdu', 'placeholder'=>lang('books_field_cdu')), set_value('book_cdu', $query->book_cdu));
						echo '</div>';
					echo '</div>';
					echo '<div class="row">';
						echo '<div class="small-5 columns">';
							echo form_label(lang('books_field_locale'));
							echo form_input(array('name'=>'book_locale', 'placeholder'=>lang('books_field_locale')), set_value('book_locale', $query->book_locale));
						echo '</div>';
						echo '<div class="small-4 columns">';
							echo form_label(lang('books_field_date'));
							echo form_input(array('name'=>'book_date', 'placeholder'=>lang('books_field_date'), 'class'=>'datetimepicker'), get_gmt_to_local_date(set_value('book_date', $query->book_date)));
						echo '</div>';
						echo '<div class="small-3 columns">';
							echo form_label(lang('books_field_price'));
							echo form_input(array('name'=>'book_price', 'placeholder'=>lang('books_field_price')), set_value('book_price', $query->book_price));
						echo '</div>';
					echo '</div>';
				echo '</div>';
				echo '<div class="small-6 columns">';
					echo form_label(lang('books_field_synopsis'));
					echo form_textarea(array('name'=>'book_synopsis', 'rows'=>5, 'class'=>'tinymce'), set_value('book_synopsis', $query->book_synopsis));
				echo '</div>';
			echo '</div>';
			echo form_submit(array('name'=>'save', 'class'=>'button radius tiny'), lang('books_save'));
			echo anchor('books', lang('core_cancel'), array('class'=>'alertlink'));
		echo form_hidden('book_id', $this->uri->segment(4));
		echo form_close();
		break;
	case 'details':
        if ($this->uri->segment(4) == NULL):
            set_msg('msgerror', lang('books_msg_choose_for_details'), 'error');
            redirect('books');
        endif;
        $query = $this->books->get_by_id($this->uri->segment(4))->row();
    	echo '<div class="row">';
    		echo '<div class="small-12 columns center">';
				echo '<h3><strong>'.$query->book_title.'</strong></h3>';
			echo '</div>';
    		echo '<div class="small-3 columns">';
    			echo thumb($query->book_cover, 480, 480);
    		echo '</div>';
    		echo '<div class="small-9 columns">';
				echo '<div class="row">';
					echo '<ul class="vcard small-12 columns">';
						echo '<div class="row">';
							echo '<li class="small-12 columns"><h4><small>'.lang('books_field_author').': </small>'.$query->book_author.'</h4></li>';
							echo '<li class="small-12 columns"><h4><small>'.lang('books_field_register').': </small>'.$query->book_register.'</h4></li>';
							echo '<li class="small-12 columns"><h4><small>'.lang('books_field_tags').': </small>'.str_replace(',', ', ',$query->book_tags).'</h4></li>';
							echo '<li class="small-12 columns"><h4><small>'.lang('books_field_edition').': </small>'.$query->book_edition.'</h4></li>';
							echo '<li class="small-12 columns"><h4><small>'.lang('books_field_publisher').': </small>'.$query->book_publisher.'</h4></li>';
							echo '<li class="small-12 columns"><h4><small>'.lang('books_field_year').': </small>'.$query->book_year_publisher.'</h4></li>';
							echo '<li class="small-12 columns"><h4><small>'.lang('books_field_city').': </small>'.$query->book_city_publisher.'</h4></li>';
							echo '<li class="small-12 columns"><h4><small>'.lang('books_field_n_pages').': </small>'.$query->book_number_pages.'</h4></li>';
						echo '</div>';
					echo '</ul>';
				echo '</div>';
	    	echo '</div>';
	    	echo '<div class="small-12 columns">';
	    		echo '<dl class="tabs" data-tab>';
					echo '<dd class="active"><a href="#panel2-1">'.lang('books_field_synopsis').'</a></dd>';
					echo '<dd><a href="#panel2-2">'.lang('books_details').'</a></dd>';
					echo '<dd><a href="#panel2-3">'.lang('books_field_reference').'</a></dd>';
				echo '</dl>';
				echo '<div class="tabs-content">';
					echo '<div class="content active" id="panel2-1">'.$query->book_synopsis.'</div>';
					echo '<div class="content" id="panel2-2">';
						echo '<ul class="vcard small-12 columns">';
							echo '<div class="row">';
								echo '<li class="small-12 columns"><h4><small>'.lang('books_field_keywords').': </small>'.$query->book_keywords.'</h4></li>';
								echo '<li class="small-12 columns"><h4><small>'.lang('books_field_isbn').': </small>'.$query->book_isbn.'</h4></li>';
								echo '<li class="small-12 columns"><h4><small>'.lang('books_field_cdd').': </small>'.$query->book_cdd.'</h4></li>';
								echo '<li class="small-12 columns"><h4><small>'.lang('books_field_cdu').': </small>'.$query->book_cdu.'</h4></li>';
								echo '<li class="small-12 columns"><h4><small>'.lang('books_field_locale').': </small>'.$query->book_locale.'</h4></li>';
								echo '<li class="small-12 columns"><h4><small>'.lang('books_field_date').': </small>'.get_gmt_to_local_date($query->book_date).'</h4></li>';
								echo '<li class="small-12 columns"><h4><small>'.lang('books_field_price').': </small>'.$query->book_price.'</h4></li>';
							echo '</div>';
						echo '</ul>';
					echo '</div>';
					$reference = str_replace("[title]", $query->book_title, get_setting('books_reference_model'));
                    $reference = str_replace("[author]", $query->book_author, $reference);
                    $reference = str_replace("[tags]", $query->book_tags, $reference);
                    $reference = str_replace("[language]", $query->book_language, $reference);
                    $reference = str_replace("[keywords]", $query->book_keywords, $reference);
                    $reference = str_replace("[edition]", $query->book_edition, $reference);
                    $reference = str_replace("[publisher]", $query->book_publisher, $reference);
                    $reference = str_replace("[city]", $query->book_city_publisher, $reference);
                    $reference = str_replace("[year]", $query->book_year_publisher, $reference);
                    $reference = str_replace("[pages]", $query->book_number_pages, $reference);
                    $reference = str_replace("[isbn]", $query->book_isbn, $reference);
                    $reference = str_replace("[cdd]", $query->book_cdd, $reference);
                    $reference = str_replace("[cdu]", $query->book_cdu, $reference);
                    $reference = str_replace("[synopsis]", $query->book_synopsis, $reference);
					echo '<div class="content" id="panel2-3">'.$reference.'</div>';
	    		echo '</div>';
	    	echo '</div>';
		break;
}